export const enum UserMessage {
  ACCOUNT_DELETION_FAILED = "Account deletion failed. Please try again later.",
  ACCOUNT_DELETION_SUCCESS = "Your account has been successfully deleted.",
  ACCOUNT_PAGE_LOAD_FAILED = "Failed to load account data. Please try reloading the page.",
  DELETE_ALL_OTHER_SESSIONS_FAILED = "Failed to revoke all other sessions. Please try again later.",
  DELETE_ALL_OTHER_SESSIONS_SUCCESS = "All other sessions have been revoked.",
  DELETE_ALL_SESSIONS_FAILED = "Failed to revoke all sessions. Please try again later.",
  DELETE_ALL_SESSIONS_SUCCESS = "All sessions have been revoked.",
  LOCAL_STORAGE_DISABLED = "Your browser or site settings do not allow local storage. Data will not be saved.",
  LOCAL_STORAGE_NOT_SUPPORTED = "Your browser does not support local storage. Data will not be saved.",
  LOCAL_STORAGE_QUOTA_EXCEEDED = "Insufficient storage space. Please clear browser or site data.",
  LOGIN_FAILED = "Sign-in failed. Please try again later.",
  LOGOUT_FAILED = "Sign-out failed. Please try again later.",
  LOGOUT_SUCCESS = "You’ve successfully signed out. Have a nice day!",
  REGISTRATION_FAILED = "Registration failed. Please try again later.",
  SERVICE_UNAVAILABLE = "Sorry, the server is currently unavailable. Please try again later.",
  SESSIONS_PAGE_LOAD_FAILED = "Failed to load session data. Please try reloading the page.",
  UNEXPECTED_ERROR = "An unknown error has occurred. Please try again later.",
  USERNAME_TAKEN = "Sorry, this username is not available.",
}
