name: Playwright Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    defaults:
      run:
        shell: bash # Required for Bash jobs
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install dependencies
        run: npm run install:all
      - name: Install Playwright Browsers
        run: npx --prefix=client playwright install --with-deps
      - name: Build server
        run: npm --prefix=server run build
      - name: Start Docker services
        run: docker compose up --detach
      - name: Start servers
        run: |
          npm --prefix=client run start &
          npm --prefix=server run start &
      - name: Run server tests
        run: npm --prefix=server run test
      - name: Run Playwright tests
        run: npm --prefix=client run pw
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report
          retention-days: 30
